luisbank:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../data/luisbank.duckdb'  # O arquivo do banco ficara na pasta data
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: us-east-1
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER') }}"
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD') }}"
        s3_endpoint: "{{ env_var('MINIO_S3_ENDPOINT', 'localhost:9000') }}"
        s3_use_ssl: false
        s3_url_style: path
