luisbank:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../data/luisbank.duckdb'  # O arquivo do banco ficará na pasta data
      extensions: 
        - httpfs
        - parquet
      settings:
        s3_region: us-east-1
        s3_access_key_id: admin
        s3_secret_access_key: password123
        s3_endpoint: localhost:9000
        s3_use_ssl: false
        s3_url_style: path