version: 2

models:
  - name: dim_customers
    description: "Tabela dimensional de clientes do LuisBank."
    columns:
      - name: customer_id
        description: "Chave primária do cliente."
        tests:
          - unique
          - not_null
      - name: risk_profile
        tests:
          - accepted_values:
              values: ['LOW', 'MEDIUM', 'HIGH']

  - name: dim_accounts
    description: "Tabela dimensional de contas bancárias."
    columns:
      - name: account_id
        tests:
          - unique
          - not_null
      - name: initial_balance_snapshot
        description: "Saldo no momento da carga."
        tests:
          - not_null

  - name: fct_transactions
    description: "Tabela fato contendo todas as transações financeiras."
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: amount
        description: "Valor da transação. Deve ser positivo."
        # Teste customizado simples: checa se existe valor negativo (SQL direto)
      - name: transaction_type
        tests:
          - accepted_values:
              values: ['PIX_IN', 'PIX_OUT', 'TED_IN', 'TED_OUT', 'BOLETO_PAY']